# Generated by Django 4.2.6 on 2023-10-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='allergeni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commanda.allergeni'),
        ),
    ]
