# Generated by Django 4.2.6 on 2023-11-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0002_allergeni_product_allergeni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergeni',
        ),
        migrations.AddField(
            model_name='product',
            name='allergeni',
            field=models.ManyToManyField(to='commanda.allergeni'),
        ),
    ]
