# Generated by Django 4.2.6 on 2023-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0003_remove_product_allergeni_product_allergeni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergeni',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='product',
            name='allergeni',
            field=models.ManyToManyField(null=True, to='commanda.allergeni'),
        ),
    ]
