# Generated by Django 4.2.6 on 2023-11-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0004_alter_allergeni_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergeni',
            field=models.ManyToManyField(blank=True, null=True, to='commanda.allergeni'),
        ),
    ]
