# Generated by Django 4.2.6 on 2023-11-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0005_alter_product_allergeni'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tipo_prodotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commanda.tipoprodotto'),
        ),
    ]
