# Generated by Django 4.2.6 on 2023-11-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
