# Generated by Django 4.2.6 on 2023-11-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergeni',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
