# Generated by Django 4.2.6 on 2023-11-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0011_commanda_conto_contobakup_tavolo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
    ]
