# Generated by Django 4.2.6 on 2023-11-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0012_alter_collection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tipo_prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.tipoprodotto'),
        ),
    ]
