# Generated by Django 4.2.6 on 2023-11-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0014_productallergeni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAllergeni',
        ),
    ]
