# Generated by Django 4.2.6 on 2023-11-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0015_delete_productallergeni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergeni',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='commanda',
            name='product',
        ),
        migrations.AddField(
            model_name='commanda',
            name='product',
            field=models.ManyToManyField(to='commanda.product'),
        ),
    ]
