# Generated by Django 4.2.6 on 2023-11-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0016_alter_allergeni_options_remove_commanda_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commanda',
            name='product',
        ),
    ]
