# Generated by Django 4.2.6 on 2023-11-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0017_remove_commanda_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanda',
            name='product',
            field=models.ManyToManyField(to='commanda.product'),
        ),
    ]
