# Generated by Django 4.2.6 on 2023-11-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0018_commanda_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commanda',
            name='quantity',
        ),
    ]
