# Generated by Django 4.2.6 on 2023-11-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0019_remove_commanda_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.product')),
                ('tavolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commanda.tavolo')),
            ],
        ),
        migrations.DeleteModel(
            name='Commanda',
        ),
    ]
