# Generated by Django 4.2.6 on 2023-12-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0022_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='quantity',
        ),
    ]
