# Generated by Django 4.2.6 on 2023-12-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0023_remove_ordine_product_remove_ordine_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commanda.tavolo', unique=True),
        ),
        migrations.CreateModel(
            name='ElementoOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.ordine')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.product')),
            ],
        ),
    ]
