# Generated by Django 4.2.6 on 2023-12-11 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0024_alter_ordine_tavolo_elementoordine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='ordine',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordine',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.tavolo', unique=True),
        ),
    ]
