# Generated by Django 4.2.6 on 2023-12-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0025_ordine_payment_status_ordine_placed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprodotto',
            name='collection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='commanda.collection'),
        ),
    ]
