# Generated by Django 4.2.6 on 2023-12-11 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0026_tipoprodotto_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoprodotto',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.collection'),
        ),
    ]
