# Generated by Django 4.2.6 on 2023-12-17 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0028_alter_tipoprodotto_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.tavolo'),
        ),
    ]
