# Generated by Django 4.2.6 on 2023-12-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0029_alter_ordine_tavolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergeni',
            field=models.ManyToManyField(blank=True, to='commanda.allergeni'),
        ),
    ]
