# Generated by Django 4.2.6 on 2023-12-18 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0030_alter_product_allergeni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commanda.product')),
                ('tavolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commanda.tavolo')),
            ],
        ),
    ]
