# Generated by Django 4.2.6 on 2023-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0031_commanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conto',
            name='tavolo',
        ),
        migrations.DeleteModel(
            name='ContoBakup',
        ),
        migrations.RemoveField(
            model_name='elementoordine',
            name='order',
        ),
        migrations.RemoveField(
            model_name='elementoordine',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='tavolo',
        ),
        migrations.AddField(
            model_name='commanda',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='Conto',
        ),
        migrations.DeleteModel(
            name='ElementoOrdine',
        ),
        migrations.DeleteModel(
            name='Ordine',
        ),
    ]
