# Generated by Django 4.2.6 on 2023-12-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0032_remove_conto_tavolo_delete_contobakup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commanda',
            name='payment_status',
        ),
    ]
