# Generated by Django 4.2.6 on 2023-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0033_remove_commanda_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tavolo',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
