# Generated by Django 4.2.6 on 2023-12-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0034_alter_tavolo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanda',
            name='tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commanda.tavolo', unique=True),
        ),
    ]
