# Generated by Django 4.2.6 on 2024-01-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0038_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanda',
            name='production_status',
            field=models.CharField(choices=[('P', 'SuCommanda'), ('S', 'InProduzione'), ('C', 'Fatto')], default='P', max_length=1),
        ),
    ]
