# Generated by Django 4.2.6 on 2024-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0039_commanda_production_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavolo',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
