# Generated by Django 4.2.6 on 2024-01-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0040_tavolo_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanda',
            name='note',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
