# Generated by Django 4.2.6 on 2024-01-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0043_alter_commanda_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanda',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
