# Generated by Django 4.2.6 on 2024-01-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0044_alter_commanda_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanda',
            name='production_status',
            field=models.CharField(choices=[('A', 'SuCommanda'), ('B', 'InProduzione'), ('C', 'ProduzioneCompletata'), ('D', 'Servito')], default='A', max_length=1),
        ),
    ]
