# Generated by Django 4.2.6 on 2024-02-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0045_alter_commanda_production_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavolo',
            name='coperti',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commanda.product')),
            ],
        ),
    ]
