# Generated by Django 4.2.6 on 2024-04-08 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0046_tavolo_coperti_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
