# Generated by Django 4.2.6 on 2024-04-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commanda', '0047_commanda_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commanda',
            name='created_at',
        ),
    ]
